#!/usr/bin/env bash

red=$'\033[31m'
green=$'\033[32m'
rst=$'\033[m'

regex_titlecase_verb='^[A-Z][a-z]+ '
regex_imperative_verb='^[A-Z][a-z]+ed '
error_msg1="${red}Commit message format is incorrect (must start with titlecase verb, regex: '^[A-Z][a-z]+ '). Example: '${green}Add feature${rst}${red}' or '${green}Update file${rst}${red}'${rst}."
error_msg2="${red}Commit message format is incorrect (use imperative verb form). Example: '${green}Add feature${rst}${red}' or '${green}Update file${rst}${red}'${rst}."

if ! grep -qE -e "$regex_titlecase_verb" "$1" ; then
    echo "$error_msg1" >&2
    exit 1
elif grep -qE -e "$regex_imperative_verb" "$1" ; then
    echo "$error_msg2" >&2
    exit 2
fi
