#!/bin/sh
# Resets the hooks path to the default, which will disable all hooks in this directory

set -eu

die () {
	printf '\033[31mError: %s\033[m\n' "${1:-"Script $0 exited with unknown error"}"
	exit 1
}

git_path=$(git rev-parse --show-toplevel) || { echo "You're not in a git repo, can't reset hooks"; exit 1; }

printf 'You are in this repository: %s\n' "$git_path"
printf 'And the hooks path will be reset\n'
printf 'Do you want to continue? (Y/n) '
read -r choice
choice=$(printf %s "$choice" | tr Y y | xargs)
[ "$choice" = y ] || [ -z "$choice" ] || { echo "Will not reset hooks path"; exit 2; }

git config --local --unset core.hooksPath || die "Failed to reset hooks path"

echo "Hooks path was reset"
